import React from "react";
import HomeRoundedIcon from "@mui/icons-material/HomeRounded";
import UploadRoundedIcon from "@mui/icons-material/UploadRounded";
import DownloadRoundedIcon from "@mui/icons-material/DownloadRounded";
import ArticleRoundedIcon from "@mui/icons-material/ArticleRounded";
import KeyboardArrowDownRoundedIcon from "@mui/icons-material/KeyboardArrowDownRounded";
import KeyboardArrowUpRoundedIcon from "@mui/icons-material/KeyboardArrowUpRounded";
import KeyboardArrowLeftRoundedIcon from "@mui/icons-material/KeyboardArrowLeftRounded";
import KeyboardArrowRightRoundedIcon from "@mui/icons-material/KeyboardArrowRightRounded";
import WorkRoundedIcon from "@mui/icons-material/WorkRounded";
import InventoryRoundedIcon from "@mui/icons-material/InventoryRounded";
import VideocamRoundedIcon from "@mui/icons-material/VideocamRounded";
import FactCheckRoundedIcon from "@mui/icons-material/FactCheckRounded";
import AccessTimeRoundedIcon from "@mui/icons-material/AccessTimeRounded";
import AttachMoneyRoundedIcon from "@mui/icons-material/AttachMoneyRounded";
import ShieldRoundedIcon from "@mui/icons-material/ShieldRounded";
import RefreshRoundedIcon from "@mui/icons-material/RefreshRounded";
import CancelRoundedIcon from "@mui/icons-material/CancelRounded";
import LockRoundedIcon from "@mui/icons-material/LockRounded";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import DeleteRoundedIcon from "@mui/icons-material/DeleteRounded";
import RestartAltRoundedIcon from "@mui/icons-material/RestartAltRounded";
import VisibilityRoundedIcon from "@mui/icons-material/VisibilityRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import MenuBookRoundedIcon from "@mui/icons-material/MenuBookRounded";
import BalanceRoundedIcon from "@mui/icons-material/BalanceRounded";
import GppMaybeRoundedIcon from "@mui/icons-material/GppMaybeRounded";
import GavelRoundedIcon from "@mui/icons-material/GavelRounded";
import CheckRoundedIcon from "@mui/icons-material/CheckRounded";
import CloseRoundedIcon from "@mui/icons-material/CloseRounded";
import ImageRoundedIcon from "@mui/icons-material/ImageRounded";
import InfoRoundedIcon from "@mui/icons-material/InfoRounded";
import OpenInNewRoundedIcon from "@mui/icons-material/OpenInNewRounded";
import ArrowBackRoundedIcon from "@mui/icons-material/ArrowBackRounded";
import ArrowForwardRoundedIcon from "@mui/icons-material/ArrowForwardRounded";
import PeopleRoundedIcon from "@mui/icons-material/PeopleRounded";
import BoltRoundedIcon from "@mui/icons-material/BoltRounded";
import LightbulbRoundedIcon from "@mui/icons-material/LightbulbRounded";
import PaletteRoundedIcon from "@mui/icons-material/PaletteRounded";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import RadioButtonUncheckedRoundedIcon from "@mui/icons-material/RadioButtonUncheckedRounded";
import RemoveRoundedIcon from "@mui/icons-material/RemoveRounded";
import ViewSidebarRoundedIcon from "@mui/icons-material/ViewSidebarRounded";
import DragIndicatorRoundedIcon from "@mui/icons-material/DragIndicatorRounded";
import MoreHorizRoundedIcon from "@mui/icons-material/MoreHorizRounded";

type P = { className?: string; style?: React.CSSProperties };

const w = (Icon: React.ComponentType<any>) =>
  ({ className, style }: P) => (
    <Icon className={className} style={{ fontSize: "inherit", ...style }} />
  );

// Named exports matching lucide-react API (same names, MUI Rounded icons)
export const Home = w(HomeRoundedIcon);
export const Upload = w(UploadRoundedIcon);
export const Download = w(DownloadRoundedIcon);
export const FileText = w(ArticleRoundedIcon);
export const ChevronDown = w(KeyboardArrowDownRoundedIcon);
export const ChevronUp = w(KeyboardArrowUpRoundedIcon);
export const ChevronLeft = w(KeyboardArrowLeftRoundedIcon);
export const ChevronRight = w(KeyboardArrowRightRoundedIcon);
export const Briefcase = w(WorkRoundedIcon);
export const Package = w(InventoryRoundedIcon);
export const Video = w(VideocamRoundedIcon);
export const FileCheck = w(FactCheckRoundedIcon);
export const Clock = w(AccessTimeRoundedIcon);
export const DollarSign = w(AttachMoneyRoundedIcon);
export const Shield = w(ShieldRoundedIcon);
export const RefreshCw = w(RefreshRoundedIcon);
export const XCircle = w(CancelRoundedIcon);
export const Lock = w(LockRoundedIcon);
export const Plus = w(AddRoundedIcon);
export const Trash2 = w(DeleteRoundedIcon);
export const RotateCcw = w(RestartAltRoundedIcon);
export const Eye = w(VisibilityRoundedIcon);
export const Edit3 = w(EditRoundedIcon);
export const BookOpen = w(MenuBookRoundedIcon);
export const Scale = w(BalanceRoundedIcon);
export const ShieldAlert = w(GppMaybeRoundedIcon);
export const Gavel = w(GavelRoundedIcon);
export const Check = w(CheckRoundedIcon);
export const X = w(CloseRoundedIcon);
export const FileImage = w(ImageRoundedIcon);
export const Info = w(InfoRoundedIcon);
export const ExternalLink = w(OpenInNewRoundedIcon);
export const ArrowLeft = w(ArrowBackRoundedIcon);
export const ArrowRight = w(ArrowForwardRoundedIcon);
export const Users = w(PeopleRoundedIcon);
export const Zap = w(BoltRoundedIcon);
export const Lightbulb = w(LightbulbRoundedIcon);
export const Palette = w(PaletteRoundedIcon);
export const Search = w(SearchRoundedIcon);
export const MoreHorizontal = w(MoreHorizRoundedIcon);

// "Icon" suffix aliases used by shadcn/ui primitives
export const CheckIcon = Check;
export const ChevronDownIcon = ChevronDown;
export const ChevronUpIcon = ChevronUp;
export const ChevronLeftIcon = ChevronLeft;
export const ChevronRightIcon = ChevronRight;
export const CircleIcon = w(RadioButtonUncheckedRoundedIcon);
export const XIcon = X;
export const SearchIcon = Search;
export const MinusIcon = w(RemoveRoundedIcon);
export const PanelLeftIcon = w(ViewSidebarRoundedIcon);
export const GripVerticalIcon = w(DragIndicatorRoundedIcon);
export const ArrowLeftIcon = ArrowLeft;
export const ArrowRightIcon = ArrowRight;
export const MoreHorizontalIcon = MoreHorizontal;
